import { DEFAULT_COUNTRY } from './constants'
import type { ApplicationFormState } from './types'

const emptyAddress = {
  line1: '',
  line2: '',
  cityOrIsland: '',
  postalCode: '',
  country: DEFAULT_COUNTRY,
}

export const defaultApplicationFormState: ApplicationFormState = {
  accountType: '',
  firstName: '',
  middleName: '',
  lastName: '',
  dateOfBirth: '',
  nationality: DEFAULT_COUNTRY,
  countryOfResidence: DEFAULT_COUNTRY,
  taxResidenceCountry: DEFAULT_COUNTRY,
  email: '',
  mobilePhone: '',
  secondaryPhone: '',
  residentialAddress: { ...emptyAddress },
  sameAsResidentialMailing: true,
  mailingAddress: { ...emptyAddress },
  idDocumentType: '',
  idDocumentNumber: '',
  idIssuingCountry: DEFAULT_COUNTRY,
  idExpiryDate: '',
  proofOfAddressType: '',
  proofOfAddressIssueDate: '',
  sourceOfFundsType: '',
  sourceOfFundsDescription: '',
  sourceOfFundsMonthlyEstimate: '',
  initialDepositAmount: '',
  initialDepositCurrency: 'USD',
  initialDepositMethod: '',
  employmentStatus: '',
  employerName: '',
  jobTitle: '',
  purposeOfAccount: '',
  preferredBranch: '',
  pepDeclaration: false,
  termsAccepted: false,
  privacyAccepted: false,
  amlAccepted: false,
  dataProcessingAccepted: false,
  marketingConsent: false,
}
